version: 2
updates:
# Maintain dependencies for Maven
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
  
# Maintain dependencies for GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    
# Maintain dependencies for Maven declared in archetype
- package-ecosystem: maven
  directory: "/src/main/resources/archetype-resources"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
